### ISSUE TITLE
Students looking for information on the client

### ISSUE THREAD

**Issue by FroZeniNside** [bitcraze/crazyflie2-ios-client#1]
Hello

I am a student at Florida Southern college working with a team on a Software Engineering project. The project we chose was to attempt to add core motion to augment this Crazyflie controller to make it more natural to use. We are having some issues getting feedback from the drones sensors and cannot find documentation with information about it. 

Could give us some information?

Thanks

**Comment by ataffanel** [comment]
Hi,

Getting sensor values from the Crazyflie is done using the log framework described here: http://wiki.bitcraze.se/doc:crazyflie:crtp:log However this is not implemented yet in ios and the current realeased firmware has a bug that will prevent from using LOG with Bluetooth LE (it is fixed in the source repos but not released yet).

Anyway, to control Crazyflie with core motion you do not need the copter sensor readings, you can send set-points in degree and the Crazyflie will follow these set-points. The set-points are sent here: https://github.com/bitcraze/crazyflie2-ios-client/blob/master/Crazyflie%20client/ViewController.m#L343 I guess this is the function you will want to modify.

**Comment by ocb00999** [comment]
Is the source code in the GitHub now working with log framework for iOS client? So that means if I flash the source code now, I can get the bitcraze sensor data from my iPhone?

**Comment by ataffanel** [comment]
No, there has been no work on log/param for ios yet.

**Comment by lucho-yankov** [comment]
Hi,

I want to expand the functionality of the iOS client and to use the logging framework, but so far I could not get back any characteristics with log data to work.
 
Can I use the logging framework over BLE by modifying only the iOS client or do I need to dig into the crazyflie-firmware and the nrf-firmware to make them support this functionality?

(To be more specific what I want to achieve is to make the iOS client capable of compensating for any accidental twists on the vertical axis during flight).
