### ISSUE TITLE
A way to comunicate with a Expansion deck via Bluetooth

### ISSUE THREAD

**Issue by EMart002** [bitcraze/crazyflie2-ios-client#16]
When developing an expansion deck, i'd prefer to communicate with the expansion deck via bluetooth rather than the crazyflie dongle because on an iOS Device i have no other option, so i can write expansions on iOS and Android that directly communicate with those expansions. 

The prior communication is of course used to control the crazyflie but i'd like to use the rest of the band width for other modules e.g. a cmos camera module with onboard image compression or a temperature sensor.

**Comment by ataffanel** [comment]
The easiest way to communicate with a deck driver is via Log and Param, if those are implemented in the iOS client it will allows to read things like temperature sensors.

For the camera it is going to be a bit more complicated since there is no ready-made protocol for this kind of data yet. We are currently looking at making the memory subsystem (used to read/write the Crazyflie configuration) easy to use to transfers data-structure.

**Comment by rbfigueira** [comment]
Hi @ataffanel can you explain more about "The easiest way to communicate with a deck driver is via Log and Param"?  Log and Param ? Can you be more clear and share some links about that ? I'm newbie in Crazyflie development. ;) Thanks

**Comment by ataffanel** [comment]
[Log](https://wiki.bitcraze.io/projects:crazyflie:firmware:log) and [param](https://wiki.bitcraze.io/doc:crazyflie:crtp:param) are subsystems implemented in the crazyflie. They are designed to allow easy communication between a client and the Crazyflie firmware. They are extensively used by the python crazyflie client to display telemetry and control the Crazyflie.

One challenge will be to implement them in the ios client using bluetooth low energy since we do not have a lot of bandwidth using bluetooth on iOS.

**Comment by EricCiocca** [comment]
Sorry to dig up an old post, but I was wondering if the BLE communication has been implemented in the year+ since this last post? I am trying to communicate with a deck of my own via bluetooth and I'm getting garbled/zeroed out data when I try to read anything. I have tried using both the logs and also writing my own CRTP endpoint with no success.

**Comment by ataffanel** [comment]
No problem for digging the post, it is still open so it should be live.

There has been no work as far as I know in implementing log/param in ios. The downlink is implemented and working since it is used by the bootloader. Since it is your own deck, the easiest should be to create your own CRTP packet so that you do not have to care about log/param and can minimize the communication flow.

One major problem with the current iOS bluetooth implementation is that it is designed to drop uplink packet that comes too fast: if you want uplink the communication part needs to be addapted to not drop your packets. If you only want downlink, there should be enough code already to get your packet back.

Can you share some code/branch where you try to get data back from the Crazyflie so that I can try to look at what could go wrong?

**Comment by knmcguire** [comment]
Do we ever want to support this? We are not planning to implement this in the immediate future.
